spring:
  application:
    name: shinhodeung
  datasource:
    url: ${DB_ENDPOINT}
    username: ${DB_USERID}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  test:
    database:
      replace: none  # 실제 DB를 사용하려면 이 옵션을 사용

server:
  port: 8080